In [ ]:
import numpy as np

In [ ]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[1]])

In [ ]:
X.shape

(4, 2)

In [ ]:
y.shape

(4, 1)

In [ ]:
w = np.random.uniform(size = (X.shape[1],y.shape[1]))

In [ ]:
b = np.random.uniform(size = y.shape)

In [ ]:
b

array([[0.56460904],
       [0.97984475],
       [0.10211466],
       [0.98927647]])

In [ ]:
w

array([[0.30165994],
       [0.59775801]])

In [ ]:
y_pred = X.dot(w) + b

In [ ]:
sigmoid = 1/(1+ np.exp(-y_pred))
z = 1/(1+ np.exp(y))

In [ ]:
print(sigmoid)
print(z)

[[0.63751831]
 [0.82886474]
 [0.59959421]
 [0.8686066 ]]
[[0.5       ]
 [0.26894142]
 [0.26894142]
 [0.26894142]]


In [ ]:
E = 0
for i in range(4):
  E += .5*(y[i]-sigmoid[i])**2

In [ ]:
E

array([0.30665295])

In [ ]:
(-1* (y - z) * (sigmoid * (1 - sigmoid))).shape

(4, 1)

In [ ]:
X.T.dot((-1* (y - z) * (sigmoid * (1 - sigmoid))))

array([[-0.25894838],
       [-0.1871343 ]])

In [ ]:
X.shape

(4, 2)

In [ ]:
w

array([[0.30165994],
       [0.59775801]])